package ConnectorCorba;


/**
* ConnectorCorba/ClientCorbaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from komblacorba.idl
* Monday, December 7, 2020 10:53:30 AM CET
*/

public interface ClientCorbaOperations 
{
  void modelChanged (ConnectorCorba.CorbaDynamicGameModel model);
} // interface ClientCorbaOperations
