package ConnectorCorba;

/**
* ConnectorCorba/ClientCorbaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from komblacorba.idl
* Monday, December 7, 2020 10:53:30 AM CET
*/

public final class ClientCorbaHolder implements org.omg.CORBA.portable.Streamable
{
  public ConnectorCorba.ClientCorba value = null;

  public ClientCorbaHolder ()
  {
  }

  public ClientCorbaHolder (ConnectorCorba.ClientCorba initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ConnectorCorba.ClientCorbaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ConnectorCorba.ClientCorbaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ConnectorCorba.ClientCorbaHelper.type ();
  }

}
