package ConnectorCorba;


/**
* ConnectorCorba/CorbaDynamicGameModelHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from komblacorba.idl
* Monday, December 7, 2020 10:53:30 AM CET
*/

abstract public class CorbaDynamicGameModelHelper
{
  private static String  _id = "IDL:ConnectorCorba/CorbaDynamicGameModel:1.0";

  public static void insert (org.omg.CORBA.Any a, ConnectorCorba.CorbaDynamicGameModel that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ConnectorCorba.CorbaDynamicGameModel extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_longlong);
          _members0[0] = new org.omg.CORBA.StructMember (
            "frame",
            _tcOf_members0,
            null);
          _tcOf_members0 = ConnectorCorba.PlayerHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_array_tc (10, _tcOf_members0 );
          _members0[1] = new org.omg.CORBA.StructMember (
            "player",
            _tcOf_members0,
            null);
          _tcOf_members0 = ConnectorCorba.SpriteHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_array_tc (10, _tcOf_members0 );
          _members0[2] = new org.omg.CORBA.StructMember (
            "sprite",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ConnectorCorba.CorbaDynamicGameModelHelper.id (), "CorbaDynamicGameModel", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ConnectorCorba.CorbaDynamicGameModel read (org.omg.CORBA.portable.InputStream istream)
  {
    ConnectorCorba.CorbaDynamicGameModel value = new ConnectorCorba.CorbaDynamicGameModel ();
    value.frame = istream.read_longlong ();
    value.player = new ConnectorCorba.Player[10];
    for (int _o0 = 0;_o0 < (10); ++_o0)
    {
      value.player[_o0] = ConnectorCorba.PlayerHelper.read (istream);
    }
    value.sprite = new ConnectorCorba.Sprite[10];
    for (int _o1 = 0;_o1 < (10); ++_o1)
    {
      value.sprite[_o1] = ConnectorCorba.SpriteHelper.read (istream);
    }
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ConnectorCorba.CorbaDynamicGameModel value)
  {
    ostream.write_longlong (value.frame);
    if (value.player.length != (10))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    for (int _i0 = 0;_i0 < (10); ++_i0)
    {
      ConnectorCorba.PlayerHelper.write (ostream, value.player[_i0]);
    }
    if (value.sprite.length != (10))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    for (int _i1 = 0;_i1 < (10); ++_i1)
    {
      ConnectorCorba.SpriteHelper.write (ostream, value.sprite[_i1]);
    }
  }

}
