package ConnectorCorba;


/**
* ConnectorCorba/CorbaDynamicGameModel.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from komblacorba.idl
* Monday, December 7, 2020 10:53:30 AM CET
*/

public final class CorbaDynamicGameModel implements org.omg.CORBA.portable.IDLEntity
{
  public long frame = (long)0;
  public ConnectorCorba.Player player[] = null;
  public ConnectorCorba.Sprite sprite[] = null;

  public CorbaDynamicGameModel ()
  {
  } // ctor

  public CorbaDynamicGameModel (long _frame, ConnectorCorba.Player[] _player, ConnectorCorba.Sprite[] _sprite)
  {
    frame = _frame;
    player = _player;
    sprite = _sprite;
  } // ctor

    

} // class CorbaDynamicGameModel
