package ConnectorCorba;

/**
* ConnectorCorba/CorbaDynamicGameModelHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from komblacorba.idl
* Monday, December 7, 2020 10:53:30 AM CET
*/

public final class CorbaDynamicGameModelHolder implements org.omg.CORBA.portable.Streamable
{
  public ConnectorCorba.CorbaDynamicGameModel value = null;

  public CorbaDynamicGameModelHolder ()
  {
  }

  public CorbaDynamicGameModelHolder (ConnectorCorba.CorbaDynamicGameModel initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ConnectorCorba.CorbaDynamicGameModelHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ConnectorCorba.CorbaDynamicGameModelHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ConnectorCorba.CorbaDynamicGameModelHelper.type ();
  }

}
