package ConnectorCorba;

/**
* ConnectorCorba/ServerCorbaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from komblacorba.idl
* Monday, December 7, 2020 10:53:30 AM CET
*/

public final class ServerCorbaHolder implements org.omg.CORBA.portable.Streamable
{
  public ConnectorCorba.ServerCorba value = null;

  public ServerCorbaHolder ()
  {
  }

  public ServerCorbaHolder (ConnectorCorba.ServerCorba initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ConnectorCorba.ServerCorbaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ConnectorCorba.ServerCorbaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ConnectorCorba.ServerCorbaHelper.type ();
  }

}
