package ConnectorCorba;


/**
* ConnectorCorba/ServerCorbaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from komblacorba.idl
* Monday, December 7, 2020 10:53:30 AM CET
*/

public interface ServerCorbaOperations 
{
  ConnectorCorba.CorbaStartGameInfo connect (String playerName, ConnectorCorba.ClientCorba client);
  void moveLeft (int playerId);
  void moveRight (int playerId);
  void moveUp (int playerId);
  void moveDown (int playerId);
} // interface ServerCorbaOperations
