package ConnectorCorba;


/**
* ConnectorCorba/Sprite.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from komblacorba.idl
* Monday, December 7, 2020 10:53:30 AM CET
*/

public final class Sprite implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String kind = null;
  public String name = null;
  public int playerid = (int)0;
  public double direction = (double)0;

  public Sprite ()
  {
  } // ctor

  public Sprite (int _id, String _kind, String _name, int _playerid, double _direction)
  {
    id = _id;
    kind = _kind;
    name = _name;
    playerid = _playerid;
    direction = _direction;
  } // ctor

} // class Sprite
